### ISSUE TITLE
Derive Copy and Clone for Query

### ISSUE THREAD

**Issue by ThalusA** [arcnmx/ddc-hi-rs#6]
Hey is this possible to derive Copy and Clone for this Query enum ? 
https://github.com/arcnmx/ddc-hi-rs/blob/master/src/lib.rs#L306

**Comment by arcnmx** [comment]
Yeah that type shouldn't be missing derives, but it can't be `Copy` due to String and Box, just `Clone`

**Comment by ThalusA** [comment]
Thanks a lot :D
